name: BOT13

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest            - name: BOT13
  uses: actions/upload-artifact@v4.0.0
  with:
    name: BOT13
    path: https://github.com/paslaframework/BOT13_mobileapps/tree/main/aplikasimobile
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail
  
    compression-level: # optional, default is 6
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
